# Generated by Django 5.1.7 on 2025-04-01 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_name', models.CharField(default='', max_length=200)),
                ('house', models.CharField(choices=[('Unicorn', 'Unicorn'), ('Pegasus', 'Pegasus'), ('Phoenix', 'Phoenix'), ('Centaur', 'Centaur'), ('None', 'None')], default='None', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
