# Generated by Django 5.1.7 on 2025-05-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='voter_class',
            field=models.CharField(default='', max_length=200),
        ),
    ]
