# Generated by Django 5.1.7 on 2025-04-01 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=200)),
                ('is_house_captain', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('house', models.CharField(choices=[('Unicorn', 'Unicorn'), ('Pegasus', 'Pegasus'), ('Phoenix', 'Phoenix'), ('Centaur', 'Centaur'), ('None', 'Not a House Captain')], default='None', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('motto', models.CharField(default='', max_length=300)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.post')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
